# Generated by Django 3.2.7 on 2021-09-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='evento',
            new_name='evento_id',
        ),
    ]
