# Generated by Django 3.2.7 on 2021-09-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_evento_local_evento_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='evento_id',
            new_name='evento',
        ),
    ]
