# Generated by Django 3.2.7 on 2021-09-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_evento_id_local_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local',
        ),
    ]
