# Generated by Django 3.2.7 on 2021-09-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evento_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='onde',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
